# This is an appspec.yml template file for use with AWS CodeDeploy.
version: 0.0
os: linux
files:
  - source: ./personal-site-dotnet.conf
    destination: /etc/init/
  - source: ./content
    destination: /srv/personal-site-dotnet
hooks:
  ApplicationStart:
    - location: ./scripts/start-site.sh
      runas: root
  ApplicationStop:
    - location: ./scripts/stop-site.sh
      runas: root
